# Generated by Django 5.2.6 on 2025-09-04 03:36

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('ratings', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
            options={
                'db_table': 'pois',
                'indexes': [models.Index(fields=['coordinate'], name='poi_coordinate_idx')],
            },
        ),
    ]
