# Generated by Django 5.2.6 on 2025-09-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
