# Generated by Django 5.2.6 on 2025-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_poi_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='source_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
