# Generated by Django 5.2.6 on 2025-09-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0003_poi_source_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
