# Generated by Django 5.2.6 on 2025-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0004_alter_poi_external_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'verbose_name': 'Point of Interest', 'verbose_name_plural': 'Points of Interest'},
        ),
        migrations.AlterField(
            model_name='poi',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='poi',
            constraint=models.UniqueConstraint(fields=('source_path', 'external_id'), name='unique_source_external_id'),
        ),
    ]
